# This file was generated by GoReleaser. DO NOT EDIT.
class Conftest < Formula
  desc "Test your configuration using Open Policy Agent"
  homepage "https://github.com/instrumenta/conftest"
  url "https://github.com/instrumenta/conftest/releases/download/v0.4.2/conftest_0.4.2_Darwin_x86_64.tar.gz"
  version "0.4.2"
  sha256 "ca56d1d5bfb537e27804d889aad55798f47cda25b50887428f7aabacc2bf329e"

  def install
    bin.install "conftest"
  end

  test do
    system "#{bin}/conftest --version"
  end
end
