# This file was generated by GoReleaser. DO NOT EDIT.
class Conftest < Formula
  desc "Test your configuration using Open Policy Agent"
  homepage "https://github.com/instrumenta/conftest"
  version "0.16.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/instrumenta/conftest/releases/download/v0.16.0/conftest_0.16.0_Darwin_x86_64.tar.gz"
    sha256 "df3f057cb7c2d4925315d69d43d9c23bdf13db30068235d40a2dc9b0f96a5d65"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/instrumenta/conftest/releases/download/v0.16.0/conftest_0.16.0_Linux_x86_64.tar.gz"
      sha256 "b3679d284dfab05a110236b72ffec447b1d77766ca74953c23ba1f0292473e94"
    end
  end

  def install
    bin.install "conftest"
  end

  test do
    system "#{bin}/conftest --version"
  end
end
