# This file was generated by GoReleaser. DO NOT EDIT.
class Kubeval < Formula
  desc "Validate your Kubernetes configurations"
  homepage "https://github.com/instrumenta/kubeval"
  version "0.11.0"

  if OS.mac?
    url "https://github.com/instrumenta/kubeval/releases/download/0.11.0/kubeval-darwin-amd64.tar.gz"
    sha256 "99769453f547305d26a4ced4a7c96de00917ca0b43ff7d8a8fa77595cd020da0"
  elsif OS.linux?
    url "https://github.com/instrumenta/kubeval/releases/download/0.11.0/kubeval-linux-amd64.tar.gz"
    sha256 "3c5ad1787b4c7af85587dfbbc00daf96a26d93715a6b4a8944a07652e7d42280"
  end

  def install
    bin.install "kubeval"
  end

  test do
    system "#{bin}/kubeval --version"
  end
end
