# This file was generated by GoReleaser. DO NOT EDIT.
class Kubeval < Formula
  desc "Validate your Kubernetes configurations"
  homepage "https://github.com/instrumenta/kubeval"
  version "0.13.0"

  if OS.mac?
    url "https://github.com/instrumenta/kubeval/releases/download/0.13.0/kubeval-darwin-amd64.tar.gz"
    sha256 "7f1019e55d0dcaf669ddd1e88d11971acc3b9e7110d8f489518a3650a272bc58"
  elsif OS.linux?
    url "https://github.com/instrumenta/kubeval/releases/download/0.13.0/kubeval-linux-amd64.tar.gz"
    sha256 "cfdc72fe80afbf5dd190ec416fac38df4a81af8316642a1173f94db9fd812491"
  end

  def install
    bin.install "kubeval"
  end

  test do
    system "#{bin}/kubeval --version"
  end
end
